name: dp-pipe

services:
  cellprofiler:
    image: cellprofiler/cellprofiler:4.2.8
    platform: linux/amd64
    volumes:
      - ../data:/data

  deepprofiler:
    build:
      context: ..
      dockerfile: docker/deepprofiler/Dockerfile
    volumes:
      - ../data:/data

volumes:
  data:
