name: Integration Workflow

on:
  pull_request:
  push:
    branches: [main]
    tags: ["*"]
  workflow_dispatch:
    inputs:
      pytest_addopts:
        description: Extra options for pytest; use -vv for full details; see
          https://docs.pytest.org/en/latest/example/simple.html#how-to-change-command-line-options-defaults
        required: false
        default: ""

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
  PYTEST_ADDOPTS: ${{ github.event.inputs.pytest_addopts }}
  PYTHONIOENCODING: "UTF-8"
  TARGET_PYTHON_VERSION: "3.11"
  UV_CACHE_DIR: ${{ github.workspace }}/.cache/uv

jobs:
  quality-test:
    name: Lint checks
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python and environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ env.TARGET_PYTHON_VERSION }}
          cache-pre-commit: false
          cache-venv: true
          setup-uv: true
          install-deps: true
      - name: Lint with ruff
        run: uv run ruff check .

  integration-test:
    name: Pytest (Python ${{ matrix.python-version }} on ${{ matrix.os }})
    needs: quality-test
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python and environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ matrix.python-version }}
          cache-pre-commit: false
          cache-venv: true
          setup-uv: true
          install-deps: false
      - name: Install dev dependencies
        env:
          UV_PYTHON: ${{ matrix.python-version }}
        run: uv sync --frozen --all-extras --group dev
      - name: Run pytest and generate coverage report
        if: (matrix.os == 'ubuntu-24.04') && (matrix.python-version == env.TARGET_PYTHON_VERSION)
        run: uv run pytest --cov=deepprofiler --cov-report=xml ${{ github.event.inputs.pytest_addopts }}
      - name: Upload coverage to Codecov
        if: (matrix.os == 'ubuntu-24.04') && (matrix.python-version == env.TARGET_PYTHON_VERSION)
        uses: codecov/codecov-action@v4
        env:
          OS: ${{ matrix.os }}
          PYTHON: ${{ matrix.python-version }}
        with:
          files: ./coverage.xml
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          flags: unittests
          name: deepprofiler
          # See https://docs.codecov.com/docs/adding-the-codecov-token
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Run pytest
        if: (matrix.os != 'ubuntu-24.04') || (matrix.python-version != env.TARGET_PYTHON_VERSION)
        run: uv run pytest ${{ github.event.inputs.pytest_addopts }}

  zenodo-model-download-and-usage-integration-test:
    name: Zenodo model download and usage integration test
    needs: integration-test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup python and environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ env.TARGET_PYTHON_VERSION }}
          cache-pre-commit: false
          cache-venv: true
          setup-uv: true
          install-deps: false
      - name: Install dev dependencies
        env:
          UV_PYTHON: ${{ env.TARGET_PYTHON_VERSION }}
        run: uv sync --frozen --all-extras --group dev
      - name: Run Zenodo model download and usage integration tests
        run: uv run pytest -m integration -v --override-ini="addopts="

  build:
    name: Build versioned package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup python and environment
        uses: ./.github/actions/setup-env
        with:
          python-version: ${{ env.TARGET_PYTHON_VERSION }}
          cache-pre-commit: false
          cache-venv: true
          setup-uv: true
          install-deps: true
      - name: Build
        run: uv build
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: dist/*.whl
          if-no-files-found: error
          retention-days: 90
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          if-no-files-found: error
          retention-days: 90
